### ISSUE TITLE
Can't teleport though open door

### ISSUE THREAD

**Issue by sambuev** [mitchemmc/VRContentExamples#11]
Hello, I have found some bug in the door BP, when I open the door and want to teleport through the door, I have to move my hand through the door first and after that, I can teleport further. 

Another bug or maybe it's just my mistake, I have been working on archviz project and exported first test version, for some reason I cannot teleport there, ground just doesn't show any option for this. I'll look why I see it in the Editor and not in Win.EXE application.

**Comment by mitchemmc** [comment]
Still unable to reproduce this issue (as mentioned in #10), please check the collision in your level to make sure there is nothing blocking the path
