### ISSUE TITLE
EVEN HERE, There seems to be no FREE LOCOMOTION ...

### ISSUE THREAD

**Issue by NextWorldVR** [mitchemmc/VRContentExamples#16]
I am so tired of 'teleporters'...  They will be the death of VR yet. 
 There's a youtube video to 'turn the VR Template into Free Locomotion'   WHAT A JOKE,. THE TURNING TAKES YOU ON A BIG SWOOPING PUKE'Y ARC THAT EVEN MAKES ME SICK..  I SWEAR I ALMOST QUIT VR AFTER THAT 'TUTORIAL'  ....  No wonder there is really nothing (NOTHING) good in VR yet,.. Any Artist has zero hope of WRANGLING the beast that is UNREAL, the BASIC RESOURCES like a 'free VR locomotion template',   

Does ANYBODY know of a simple VR Locomotion sample project or template with PROPER TURNING?  WHY HAS UNREAL NEVER ADDED A FREE LOCOMOTION VR TEMPLATE????

Thank you for any help,..  Not sure if I'm even posting in the exact right area, I think it is an 'issue' with the tool.  A huge omission .. It is not even mentioned...  it is certainly my 'ISSUE'  :)   It's limiting my releasing an alpha build\\
Robert.

**Comment by mitchemmc** [comment]
I'm not too sure if this is the right place, but I did write an instructor guide with Epic that has an implementation of free locomotion. It's an expansion on some of the systems of my VR Cookbook and might be of use to you.

You can get it here: https://www.unrealengine.com/en-US/blog/unreal-engine-4-instructor-guides-are-now-available?sessionInvalidated=true

I'm gonna close this issue for now as it doesn't really relate to this repo but feel free to reply if you have any issues with the Content Examples themselves.
