### ISSUE TITLE
VRFunctionLibrary blueprint error. Unreal Engine 4.12.5

### ISSUE THREAD

**Issue by elianalien** [mitchemmc/VRContentExamples#2]
Hello @mitchemmc what a great work you're doing here!
I'm a noobs anyway and I'm experiencing this issue while trying to run the VR_Head_IK example map. 
![screen shot 2016-07-25 at 8 23 56 pm](https://cloud.githubusercontent.com/assets/5174784/17102875/c5f0cdaa-52a5-11e6-98d8-c19fd588f269.png)

Is there any workaround to resolve this issue? 
I'm developing in Unreal Engine 4.12.5.
is it related to the rift connection?

Thank you very much!

**Comment by mitchemmc** [comment]
Hmm it looks like you don't have the Oculus Plugin enabled?
