### ISSUE TITLE
Laggy hands

### ISSUE THREAD

**Issue by Kiefy** [mitchemmc/VRContentExamples#7]
Your content examples are awesome, but there's an odd issue with the movement of the hand spheres and any items you pick up. like they are running at a much lower fps than 90.

The visual teleport components don't exhibit this issue though.

I made a video to show what I mean. (Jump to 0:17 to skip me fumbling with the hmd)
[Dropbox: mitch_vr_hand_problem.mp4 (10 MB)](https://dl.dropboxusercontent.com/u/1315574/mitch_vr_hand_problem.mp4)
Everything is smooth and perfect, until you move your hands or pick up items.

PS. Thanks for everything you do :)

**Comment by mitchemmc** [comment]
If you type 'Stat FPS' into the console, what kind of numbers are you getting? From the frame timing panel it looks like your GPU isn't hitting the frame rate (although the judder shouldn't be this bad even at 45fps).
You could try lowering the screen percentage and trying to get 90fps and see if that helps.

I only have my Rift on me at the moment so I can't really test Vive perf, but I'm not seeing the judder on my end. 
I'll test with Vive later today and see if I can reproduce it.

**Comment by Kiefy** [comment]
It was 45 fps. and it shows I'm missing a lot of frames, so it would appear I have a performance issue with Unreal Engine, despite running on a GTX 1080.  Though it was only showing around 60% GPU usage.
[Screenshot](http://image.prntscr.com/image/ed0142dd402a4b8ebb706ed9a47c4147.png)

I migrated your map to a mobile/low quality new project and was then able to achieve 90 fps and the hand judder was gone.

Strange how only the hands were affected so badly and not anything else though.

And geez, what kind of system do you need for Unreal VR? :P

Judging by the problems everyone else seemed to have with Dishonored 2 while I happily completed the whole game at a solid 60fps on ultra graphics, I thought my system was far above average. How can anyone else be running this at 90 fps?

Sorry to bother you with my computer problems.

**Comment by Kiefy** [comment]
I went back to your project and set the r.ScreenPercentage to 100% which sped things up a lot, clearing 90 fps easily, then tried 200% and again, still holding 90 fps and looking great, but the hands were still juddering, then I bashed the motion controller on my desk trying to reach for the game cartridge and Unreal crashed. :D [Screenshot](http://image.prntscr.com/image/463a311086864abeb607ca1235b93b3b.png)

**Comment by Kiefy** [comment]
I noticed the r.ScreenPercentage is set to 280% by default. Is that something that is saved with your project or is my system doing that? Isn't that a bit overkill?

What system do you have?

**Comment by mitchemmc** [comment]
Weird my project has a default screen percentage of 140%
I tried it on my vive as well and had no issues with performance (I also have a GTX1080) I recently changed the project to the Forward renderer but that should actually be better performance than the default differed.
So in all honesty I'm not too sure, I'll keep on looking, but it's my understanding that you can't set the SP engine wide so I'm don't really know where the 280% came from (just as a side that's a total resolution of 3024x3360 per eye or 6048x6720 at 90fps or 3.7 billion pixels/second compared to the 124 million pixels/second of 1080p60 so understandable that at GTX1080 can't quite hit it)
