### ISSUE TITLE
[Request] Door/Drawer follow-through motion

### ISSUE THREAD

**Issue by Kiefy** [mitchemmc/VRContentExamples#8]
When I opened the door and drawers, I expected the movement to carry when I let go of the grab button, to be able to slam them open or shut, but they unrealistically stop dead.

It would be cool if they carried the movement velocity, the way it is in Job Simulator, etc.

**Comment by mitchemmc** [comment]
Sure, I'll put it on the roadmap.
Currently it doesn't happen as I didn't want to use physics constraints as they break easily with motion controllers so it uses simple position offsets, but I could simulate some momentum (it just might make the Blueprint a little more complicated)

**Comment by mitchemmc** [comment]
Added in 3334e0f53c3d81dd28c697e3ef03c09b40ea664d and 38f539e09cb5b2fb7f378b69ff5563dc2ea2ec2d Will be in next release
