### ISSUE TITLE
Virtual Keyboard-Backspace button not working with Web Browser widget (4.15)

### ISSUE THREAD

**Issue by CJRobertson** [mitchemmc/VRContentExamples#9]
The backspace button on the virtual keyboard example does not remove characters from web browser widget text boxes. 

I had created my own virtual keyboard in 4.14 and everything worked fine (my personal keyboard: https://www.youtube.com/watch?v=iOMRT9dZuh4). Porting the project to 4.15 broke the Enter and Backspace virtual keys but all other keys work fine. I used your project to see if your's was having the same issue which sadly it is when using 4.15. I'm pretty sure this issue is an engine bug since its not just my project having issues so I filed a bug report on Epic's Answer Hub but I'm still waiting for someone to reply.

**Bug Report:** https://answers.unrealengine.com/questions/572915/press-key-bp-node-not-emulating-enter-or-backspace.html

**Comment by CJRobertson** [comment]
Just giving an update. I finally convinced Epic that it was a bug and they entered it into the bug logger. Looks like it going fixed in 4.16 :D

https://issues.unrealengine.com/issue/UE-43370

EDIT: Confirmed that the backspace button has been fixed as of 4.16 Preview 3 :D

**Comment by mitchemmc** [comment]
Great! sorry for the lack of replying, must have missed this one. Good thing that epic has fixed it now though
